spring:
  application:
    name: "EngTeacher"
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/
      chat:
        options:
          #model: google/gemini-3.5-flash
          model: deepseek/deepseek-v4-pro
          temperature: 0.8
    chat:
      observations:
        log-prompt: true
        log-completion: true
  mongodb:
    uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGO_URL}/${MONGO_DATABASE}?authSource=admin
  threads:
    virtual:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
  observations:
    annotations:
      enabled: true
      enable:
        "http.server.requests": false # Suppress duplicate Micrometer HTTP server spans
        "http.client.requests": false # Suppress duplicate Micrometer HTTP client spans
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
          headers:
            Authorization: "Basic ${LANGFUSE_AUTH_HEADER}"
            x-langfuse-ingestion-version: "4"
